spring:
   cloud:
      gateway:
         discovery:
            locator:
               enabled: true
               lower-case-service-id: true
         globalcors:
            cors-configurations:
               '[/**]':
                  allowedOrigins: '*'
                  allowedMethods: '*'
                  allowed-headers: '*'
         routes:
         -  id: discovery-service
            uri: http://discovery-server:8761
            predicates:
            - Path=/eureka-dashboard/**
         -  id: discovery-service-static
            uri: http://discovery-server:8761
            predicates:
            - Path=/eureka/**
         -  id: user-service
            uri: lb://user-service
            predicates:
            - Path=/api/user/**
         -  id: message-service
            uri: lb://message-service
            predicates:
            - Path=/api/message/**
         -  id: payment-service
            uri: lb://payment-service
            predicates:
            - Path=/api/payment/**
         -  id: wallet-service
            uri: lb://wallet-service
            predicates:
            - Path=/api/wallet/**
   config:
      import: optional:configserver:http://config-server:8888
   main:
      web-application-type: reactive
server:
   port: '8080'
eureka:
   instance:
      hostname: api-gateway
      prefer-ip-address: true
   client:
      service-url:
         defaultZone: http://eureka-docker:eureka@discovery-server:8761/eureka